environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "1.8"
    - nodejs_version: "2.5"
    - nodejs_version: "3.3"
    - nodejs_version: "4.2"
    - nodejs_version: "5.5"
install:
  - "npm install -g mocha"
  - "npm install -g typescript"
  - "npm install -g tsd"
  - "npm install"
  - "tsd reinstall --save"
  - "npm run build"
build: off
test_script:
  - "npm run test"
version: "{build}"